name: RedCraftProtect
main: org.redcraft.redcraftprotect.RedCraftProtect
version: 0.0.1-SNAPSHOT
author: RedCraft
authors: [Nano_, lululombard]
commands:
  rplist:
    description: Lists protected
    usage: /rplist <help>
    permission: redprotect.all
