name: RedCraftProtect
main: org.redcraft.redcraftprotect.RedCraftProtect
version: 0.0.1-SNAPSHOT
api-version: 1.16
author: RedCraft
authors: [Nano_, lululombard]
website: redcraft.org
commands:
  rplist:
    description: Lists protected
    usage: /rplist <help>
    permission: redprotect.all
